//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 12:16:22 AM CEST 
//


package gui.tasks.entities.presek.izvoda;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zadaci.entities.presekIzvoda package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PresekIzvoda_QNAME = new QName("http://informatika.ftn.uns.ac.rs/xws/tim1/presekIzvoda", "Presek_izvoda");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zadaci.entities.presekIzvoda
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PresekIzvoda }
     * 
     */
    public PresekIzvoda createPresekIzvoda() {
        return new PresekIzvoda();
    }

    /**
     * Create an instance of {@link StavkaPreseka }
     * 
     */
    public StavkaPreseka createStavkaPreseka() {
        return new StavkaPreseka();
    }

    /**
     * Create an instance of {@link ZaglavljePreseka }
     * 
     */
    public ZaglavljePreseka createZaglavljePreseka() {
        return new ZaglavljePreseka();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PresekIzvoda }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://informatika.ftn.uns.ac.rs/xws/tim1/presekIzvoda", name = "Presek_izvoda")
    public JAXBElement<PresekIzvoda> createPresekIzvoda(PresekIzvoda value) {
        return new JAXBElement<PresekIzvoda>(_PresekIzvoda_QNAME, PresekIzvoda.class, null, value);
    }

}
