//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 12:16:22 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://informatika.ftn.uns.ac.rs/xws/tim1/presekIzvoda", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gui.tasks.entities.presek.izvoda;
